[rocblas] Fix schedule name for gfx1103 logics (#2539)
## Motivation

The `gfx1103` logic files used an incorrect reference to `navi33`, which
has been exposed due to the recent inclusion of new logic file
consistency checks in #2162.

## Technical Details

Update the schedule name in the rocblas logic files to properly map to
`gfx1103` which is consistent with the architectureMap in Common.py

## Test Plan

Local testing before and after this change shows the following outputs

Command:
```
Tensile/bin/TensileCreateLibrary [...] --architecture=gfx1103 /path/to/Tensile/Logic/asm_full build_gfx1103 HIP
```

Result (before; develop)
```
ValueError: Architecture mismatch: gfx1103 does not match  navi33. Review the library logic file
```

Result (after)
```
# Reading logic files: 32 thread(s), 144 tasks .............................. 100.0% (took 4.0 secs)
# Generating kernels: 32 thread(s), 2690 tasks .............................. 100.0% (took 23.1 secs)
# Compiling source kernels .............................. 100.0% (took 0.0 secs)
```

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.